// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = {
    "desktop": require("./modules/dtop"),
    "gh": require("./modules/github"),
    "homescreen": require("./modules/hscr"),
    "handwriting": require("./modules/hw"),
    "roll": require("./modules/dice")
  };

}).call(this);
